### ISSUE TITLE
Start application before running features

### ISSUE THREAD

**Issue by jurriaan** [meadsteve/white-bread#9]
Is it intentional that I have to boot my application manually?

I copied some statements from ExUnit to get my application up and running (so I could use it within the features). See
https://github.com/elixir-lang/elixir/blob/deb0eb44f2c352f46c0edc89ac819d3f4df96b10/lib/mix/lib/mix/tasks/test.ex#L148-L168

**Comment by meadsteve** [comment]
@jurriaan to be honest it's not really intentional or unintentional at the moment. I hadn't really made a decision about this.

How would you expect it to work? Would you expect it to always start the application it's testing?

I've been thinking there are some use cases when you may not want/need it to. For example if you are just using cucumber to define the business logic of your modules outside of the application.

Maybe it would be useful to have an argument going to the mix task to tell it to start the app or not.

**Comment by ericmj** [comment]
`mix test` always start the application unless you pass `--no-start`.

**Comment by meadsteve** [comment]
@ericmj good point. So I guess the least surprising thing is to do the same here.

**Comment by jurriaan** [comment]
@meadsteve :+1:

**Comment by meadsteve** [comment]
@jurriaan this is fixed now in master but  I haven't released it to hex.pm yet.
